name: 'paint'
description: 'A GitHub action to paint text in your contribution graph'
branding:
  icon: 'message-square'
  color: 'black'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  text:
    description: 'Text to display on the contribution graph'
    required: true
  token:
    description: 'GitHub personal access token with access to create/delete repositories, push commits, and read user information'
    required: true
  user:
    description: 'GitHub username to generate contribution graph for'
    required: false
  repo:
    description: 'Dummy GitHub repository to push the commits to'
    required: true
  visibility:
    description: 'Visibility of the dummy repository (public, private, internal, or visibility of the repository being painted to)'
    required: false
  git_name:
    description: 'Name to use for the git commits (defaults to name found in the GitHub user profile of the associated token)'
    required: false
  git_email:
    description: 'Email to use for the git commits (defaults to email found in the GitHub user profile of the associated token)'
    required: false
  start:
    description: 'Start date for the contribution graph (YYYY-MM-DD, defaults to today - 1y. Start rounds to the previous sunday)'
    required: false
  end:
    description: 'End date for the contribution graph (YYYY-MM-DD, defaults to today. End rounds to the next saturday)'
    required: false
  force_date:
    description: 'Skip any date rounding and force the date range to be used for the contribution graph (YYYY-MM-DD to YYYY-MM-DD format)'
    required: false
  separator:
    description: 'Separator for the contribution graph'
    required: false
    default: '|'
  inverse:
    description: 'Invert the color of the pixels on the contribution graph'
    required: false
    default: false
  repeat:
    description: 'Repeat the text on the contribution graph as many times as possible'
    required: false
    default: false
  valign:
    description: 'Vertical alignment of the text on the contribution graph (top, center, bottom)'
    required: false
    default: 'center'
  halign:
    description: 'Horizontal alignment of the text on the contribution graph (left, center, right)'
    required: false
    default: 'center'
  padding:
    description: 'Padding around the text on the contribution graph (in (top, right, bottom, left) format)'
    required: false
    default: '0 0 0 0'
  dry_run:
    description: 'Do not push any commits to the targeted repository'
    required: false
    default: false