name: 'paint'
description: 'A GitHub action to paint text in your contribution graph'
branding:
  icon: 'message-square'
  color: 'black'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  user:
    description: 'GitHub username to generate contribution graph for'
    required: true
  text:
    description: 'Text to display on the contribution graph'
    required: true
  repo:
    description: 'GitHub repository to push the contribution graph to'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'GitHub token to use to interact with GH API and push the contribution graph to the repository'
    required: false
    default: ${{ github.token }}
  start:
    description: 'Start date for the contribution graph (YYYY-MM-DD, defaults to today - 1y. Rounds to the previous sunday)'
    required: false
  end:
    description: 'End date for the contribution graph (YYYY-MM-DD, defaults to today. Rounds to the next saturday)'
    required: false
  separator:
    description: 'Separator for the contribution graph'
    required: false
    default: ' '
  inverse:
    description: 'Invert the color of the pixels on the contribution graph'
    required: false
    default: false
  repeat:
    description: 'Repeat the text on the contribution graph as many times as possible'
    required: false
    default: false
  valign:
    description: 'Vertical alignment of the text on the contribution graph (top, center, bottom)'
    required: false
    default: 'center'
  halign:
    description: 'Horizontal alignment of the text on the contribution graph (left, center, right)'
    required: false
    default: 'center'
  padding:
    description: 'Padding around the text on the contribution graph (in (top, right, bottom, left) format)'
    required: false
    default: '1 1 1 1'
  dryrun:
    description: 'Do not push the contribution graph to the repository'
    required: false
    default: false