name: Generate GitHub contributions graph
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ./paint
      with:
        user: tbrockman
        text: theo.lol
        token: ${{ secrets.GH_PAINT_PAT }}
        repo: 'github-paint-test'
        dryrun: true