name: Generate GitHub contributions graph
on: 
  schedule:
    - cron: '0 0 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip'
        - run: pip install -r requirements.txt
        - name: Run script generation CLI
          run: |
            GH_TOKEN=${{ secrets.GITHUB_PAT }} python -m src.main "tbrockman" "theo.lol" --help