name: Generate GitHub contributions graph
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ./ # replace this with a specific version of the action
      with:
        text: theo.lol
        token: ${{ secrets.GH_PAINT_PAT }}
        repo: 'github-paint-test'
        inverse: true
        git_email: 'iam@theo.lol'